### ISSUE TITLE
Repository update schedule questions.

### ISSUE THREAD

**Issue by JoonHong-Kim** [suzgunmirac/meta-prompting#1]
The paper says that the data, prompts, and model outputs are available in this repository, so when are you going to update it?

**Comment by yifanzhang-pro** [comment]
https://github.com/meta-prompting/meta-prompting

Official implementation of paper "Meta Prompting for AGI Systems" (https://arxiv.org/abs/2311.11482)

**Comment by suzgunmirac** [comment]
> The paper says that the data, prompts, and model outputs are available in this repository, �so when are you going to update it?

Hi @JoonHong-Kim, thank you very much for your interest in our work! We are planning to make our code and results publicly available in the next few days.

**Comment by JoonHong-Kim** [comment]
Thx :) I'm really intersted in your resarch.

**Comment by stashka-la** [comment]
Hello @suzgunmirac also looking forward to the code release... your paper is one of the most interesting ones I've recently read!
